baseURL = "https://bellala.org/"
languageCode = "en-us"
title = "Venkatsai Bellala"
theme = "bellala"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]
publishDir = 'docs/'
enableGitInfo = true
summaryLength = 0
[taxonomies]
    category = "categories"
    tag = "tags"
[params]
  tileColor = '#8fbcbb'
  themeColor = "#FFFFFF"
  authors = ["Venkatsai Bellala"]
  images = ["/favicons/apple-touch-icon.png"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "Advising"
    url = "/advising/"
    weight = 5

[markup]
  [markup.highlight]
  guessSyntax = true
  style = "dracula"
  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2


[services]
  [services.twitter]
    disableInlineCSS = true


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true