baseURL = "https://bellala.org/"
languageCode = "en-us"
title = "Venkatsai Bellala"
theme = "bellala"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]
publishDir = 'docs/'
enableGitInfo = true
[taxonomies]
    category = "categories"
    tag = "tags"
[params]
  tileColor = '#8fbcbb'
  themeColor = "#FFFFFF"
  authors = ["Venkatsai Bellala"]
  images = ["/favicons/apple-touch-icon.png"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Advising"
    url = "/advising/"
    weight = 4

[markup]
  [markup.highlight]
  guessSyntax = true
  style = "nord"
  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2