# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Bellala"
license = "MIT"
licenselink = "https://github.com/vskbellala/vskbellala.github.io/blob/master/LICENSE"
description = "theme for my website"
homepage = "https://bellala.org/"
tags = ['simple', 'minimal','portfolio']
features = ['system font', 'open color']
min_version = "0.41.0"

[author]
  name = "Venkatsai Bellala"
  homepage = "https://bellala.org"